/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "Core/comm/comm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CommBasicRp, CommBasicRp, AUTO)


PB_BIND(CommInterceptRq, CommInterceptRq, AUTO)


PB_BIND(CommChunkRq, CommChunkRq, AUTO)





